import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const view = fs.readFileSync(new URL('../../CornersPrediction.Web/Views/BotAutomation/Index.cshtml', import.meta.url), 'utf8');
const source = view.slice(view.indexOf('    const progressPercent ='), view.indexOf('    const renderJobs ='));
const context = vm.createContext({ Date: class extends Date { static now() { return Date.parse('2026-09-06T06:00:00Z'); } } });
vm.runInContext(source + '\nglobalThis.api={progressPercent,activityText,utcDate,jobStatusLabel};', context);
const { progressPercent, activityText, utcDate, jobStatusLabel } = context.api;
assert.equal(progressPercent({status:'Running',processedBatches:0}), null);
assert.equal(progressPercent({status:'Running',processedBatches:0,totalBatches:20,currentBatchCompletedMatches:1,currentBatchTotalMatches:10}),0.5);
assert.equal(progressPercent({status:'Running',processedBatches:1,totalBatches:10,currentBatchCompletedMatches:5,currentBatchTotalMatches:10}),15);
assert.equal(progressPercent({status:'Queued',processedBatches:1,totalBatches:10,currentBatchCompletedMatches:5,currentBatchTotalMatches:10}),10);
assert.equal(progressPercent({status:'Completed'}),100);
assert.match(activityText({status:'Running',updatedAtUtc:'2026-09-06T05:59:45'}),/hace 15s/);
assert.match(activityText({status:'Running',updatedAtUtc:'2026-09-06T05:20:00'}),/40 min.*recuperación/);
assert.equal(utcDate('2026-09-06T05:59:45').toISOString(),'2026-09-06T05:59:45.000Z');
assert.equal(utcDate('2026-09-06T01:59:45-04:00').toISOString(),'2026-09-06T05:59:45.000Z');
assert.equal(jobStatusLabel({status:'Completed',errorMatches:10}),'Finalizado con errores');
assert.equal(jobStatusLabel({status:'Completed',errorMatches:0}),'Completed');
console.log('PASS real batch progress, preparation without fake 0%, completed state and UTC heartbeat age');
