using CornersPrediction.Application.Predictions;
using CornersPrediction.Application.MatchHistory;
using CornersPrediction.Application.Teams;
using CornersPrediction.Application.Betting;
using CornersPrediction.Application.Admin;
using CornersPrediction.Application.UpcomingMatches;
using CornersPrediction.Application.AutomatedCorners;
using CornersPrediction.Application.Automation;
using CornersPrediction.Application.Automation.BotC;
using CornersPrediction.Application.Automation.BotG;
using CornersPrediction.Application.FootballIntelligence;
using CornersPrediction.Application.RobustPickEvaluation;
using CornersPrediction.Domain.RobustPickEvaluation;
using Microsoft.Extensions.DependencyInjection;

namespace CornersPrediction.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<IPredictTotalCornersUseCase, PredictTotalCornersUseCase>();
        services.AddScoped<IOverUnderPredictionUseCase, OverUnderPredictionUseCase>();
        services.AddScoped<IShotsOnGoalPredictionUseCase, ShotsOnGoalPredictionUseCase>();
        services.AddScoped<IModelDebugPredictionUseCase, ModelDebugPredictionUseCase>();
        services.AddScoped<ICreateMatchHistoryItemUseCase, CreateMatchHistoryItemUseCase>();
        services.AddScoped<IBulkCreateMatchHistoryUseCase, BulkCreateMatchHistoryUseCase>();
        services.AddScoped<IUpdateMatchHistoryItemUseCase, UpdateMatchHistoryItemUseCase>();
        services.AddScoped<IDeleteMatchHistoryItemUseCase, DeleteMatchHistoryItemUseCase>();
        services.AddScoped<IGetRecentMatchHistoryUseCase, GetRecentMatchHistoryUseCase>();
        services.AddScoped<IGetManualMatchHistoryEntriesUseCase, GetManualMatchHistoryEntriesUseCase>();
        services.AddScoped<IGetPredictionContextUseCase, GetPredictionContextUseCase>();
        services.AddScoped<IGetTeamBi3InfoUseCase, GetTeamBi3InfoUseCase>();
        services.AddScoped<IGetTeamBig3LeaguesUseCase, GetTeamBig3LeaguesUseCase>();
        services.AddScoped<IGetFormationListUseCase, GetFormationListUseCase>();
        services.AddScoped<IGetUpcomingMatchesUseCase, GetUpcomingMatchesUseCase>();
        services.AddScoped<ICreateBettingRecordUseCase, CreateBettingRecordUseCase>();
        services.AddScoped<IUpdateBettingRecordUseCase, UpdateBettingRecordUseCase>();
        services.AddScoped<IDeleteBettingRecordUseCase, DeleteBettingRecordUseCase>();
        services.AddScoped<IGetBettingRecordByIdUseCase, GetBettingRecordByIdUseCase>();
        services.AddScoped<IGetBettingRecordsUseCase, GetBettingRecordsUseCase>();
        services.AddScoped<IGetBettingSummaryUseCase, GetBettingSummaryUseCase>();
        services.AddScoped<ICreateBankrollTransactionUseCase, CreateBankrollTransactionUseCase>();
        services.AddScoped<IGetBankrollTransactionsUseCase, GetBankrollTransactionsUseCase>();
        services.AddScoped<IGetCurrentBankrollUseCase, GetCurrentBankrollUseCase>();
        services.AddScoped<IGetAutomatedCornerSelectionsUseCase, GetAutomatedCornerSelectionsUseCase>();
        services.AddScoped<IUpdateAutomatedCornerSelectionStatusUseCase, UpdateAutomatedCornerSelectionStatusUseCase>();
        services.AddScoped<IResolveAutomatedCornerSelectionUseCase, ResolveAutomatedCornerSelectionUseCase>();
        services.AddScoped<ILinkAutomatedCornerSelectionMatchUseCase, LinkAutomatedCornerSelectionMatchUseCase>();
        services.AddScoped<IDeleteAutomatedCornerSelectionUseCase, DeleteAutomatedCornerSelectionUseCase>();
        services.AddScoped<IAutomatedBotPickSettlementUseCase, AutomatedBotPickSettlementUseCase>();
        services.AddScoped<IAutomatedBotPerformanceService, AutomatedBotPerformanceService>();
        services.AddScoped<IRecommendationJobsUseCase, RecommendationJobsUseCase>();
        services.AddScoped<IRecommendationBotDefinitionsUseCase, RecommendationBotDefinitionsUseCase>();
        services.AddSingleton<IBotCPickDecisionEngine, BotCPickDecisionEngine>();
        services.AddSingleton<IBotCMetaModelPredictor, UnavailableBotCMetaModelPredictor>();
        services.AddSingleton<IBotGFeatureBuilder, BotGFeatureBuilder>();
        services.AddSingleton<IMarketProbabilityService, StrictMarketProbabilityService>();
        services.AddSingleton<IBotGCalibrationService, BotGHierarchicalCalibrationService>();
        services.AddSingleton<IBotGUncertaintyService, BotGConservativeUncertaintyService>();
        services.AddSingleton<IBotGOodService, BotGRobustOodService>();
        services.AddSingleton<IBotGExpectedValueService, BotGExpectedValueService>();
        services.AddSingleton<IBotGAbstentionService, BotGAbstentionService>();
        services.AddSingleton<IBotGSelector, BotGSelector>();
        services.AddScoped<ICreatePlatformUserUseCase, CreatePlatformUserUseCase>();
        services.AddScoped<IUpdatePlatformUserUseCase, UpdatePlatformUserUseCase>();
        services.AddScoped<IDeletePlatformUserUseCase, DeletePlatformUserUseCase>();
        services.AddScoped<IGetPlatformUserByIdUseCase, GetPlatformUserByIdUseCase>();
        services.AddScoped<IGetPlatformUsersUseCase, GetPlatformUsersUseCase>();
        services.AddScoped<IGetPlatformRolesUseCase, GetPlatformRolesUseCase>();
        services.AddSingleton<INewsQueryBuilder, FootballNewsQueryBuilder>();
        services.AddSingleton<IArticleDeduplicator, ArticleDeduplicator>();
        services.AddSingleton<IRelevantTextSelector, RelevantTextSelector>();
        services.AddSingleton<RuleBasedNewsFactExtractor>();
        services.AddSingleton<INewsFactConsolidator, NewsFactConsolidator>();
        services.AddSingleton<IPlayerImpactCalculator, PlayerImpactCalculator>();
        services.AddSingleton<IIntelligenceSnapshotBuilder, FootballIntelligenceSnapshotBuilder>();
        services.AddSingleton<IPredictionConsensusService, PredictionConsensusService>();
        services.AddSingleton<IPredictionReconciliationService, PredictionReconciliationService>();
        services.AddSingleton<IPredictiveDistributionService, EmpiricalResidualBootstrapV1>();
        services.AddSingleton<IAsianValueCalculator, AsianValueCalculator>();
        services.AddSingleton<IRobustMarketProbabilityService, RobustMarketProbabilityService>();
        services.AddSingleton<ICalibrationReliabilityService, CalibrationReliabilityService>();
        services.AddSingleton<IRobustValueEvaluationService, RobustValueEvaluationService>();
        services.AddSingleton<IRiskAdjustedStakeService, RiskAdjustedStakeService>();
        services.AddSingleton<IPortfolioExposureService, PortfolioExposureService>();
        services.AddSingleton<IRobustPickPolicyEvaluator, RobustPickPolicyEvaluator>();
        services.AddSingleton<IScenarioDataReadinessEvaluator, ScenarioDataReadinessEvaluator>();
        services.AddSingleton<IScenarioProvider, BaseScenarioProvider>();
        services.AddSingleton<IScenarioProvider, LineupScenarioProvider>();
        services.AddSingleton<IScenarioProvider, IntelligenceScenarioProvider>();
        services.AddSingleton<IScenarioProvider, FatigueScenarioProvider>();
        services.AddSingleton<IScenarioProvider, GameStateScenarioProvider>();
        services.AddSingleton<IScenarioProvider, MarketMovementScenarioProvider>();
        services.AddScoped<IRobustPickEvaluationService, RobustPickEvaluationService>();
        services.AddScoped<IRobustPickBackfillService, RobustPickBackfillService>();

        return services;
    }
}
